### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by chrisjobando** [universal-store/monorepo#2]
# Instructions
- Recreate this sign in screen, navigating to sign up page by clicking the "sign up" text. Do not worry about the forgot password button for now.

## Notes:
- The logo (purple square) should be the `purple[1]` color, and you do not need to include the shadow for now.
- The log in button does not need to perform any actions yet

![image](https://user-images.githubusercontent.com/35117309/92617911-cd7c3000-f28d-11ea-9db6-d2794cc1c276.png)

**Comment by DanielKeehn** [comment]
![SignInPage](https://user-images.githubusercontent.com/40642338/92972662-986c0b00-f450-11ea-94fc-484a096e32ed.png)
