### ISSUE TITLE
Frontend: Create user's Profile page

### ISSUE THREAD

**Issue by marie077** [universal-store/monorepo#69]
Create Profile page according to Figma design. Do not worry about populating page with data. 

https://www.figma.com/file/aCPl5eaWhbmEyVSBNTaNIq/Sprint-3?node-id=313%3A91

**Comment by DanielKeehn** [comment]
I am pretty much done with this issue expect that there are placeholder images for the profile picture and checkmark logo 

![UniversalStore_UserProfilePage](https://user-images.githubusercontent.com/40642338/95838148-709dea80-0d0f-11eb-8d6d-d6ce597f8eb4.jpg)
